name: Main

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

env:
  RUBY_VERSION: 2.7.6
  NODE_VERSION: 14.18.1
  JEKYLL_ENV: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Install Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - uses: actions/cache@v2
        with:
          path: |
            '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - name: Build
        run: bundle exec jekyll serve
